### ISSUE TITLE
Paused playback resumes just from waking the screen

### ISSUE THREAD

**Issue by anohren** [lbryio/odysee-ios#78] opened 2021-04-03 17:46 UTC
Just the action of waking the screen, i.e. using the power button to show the lock screen in order to e.g. check the time, often results in resuming playback of a recently paused video. 

I think I have only experienced this when Odysee is the foreground app at the time of locking the screen. 

It suggests that the app doesn't properly keep track of the user's latest intent to play or pause the video. Or an OS bug. 

Considering that there's only about a 50% chance I'll end up with an already playing video continuing playback after I lock the screen, perhaps the two are related. Intuitively it feels like you're doing something with the playback state whenever the screen is locked/when the app state changes, and that sometimes when locking the screen the OS suspends the app before the operation has had time to finish, resulting in it instead being performed the next time iOS preemptively wakes the app as a result of waking the screen (i.e. as a response to imminent user interaction). Just a guess.

**Comment by Adlai-Holler** [comment] 2021-06-24 20:10
Think this is a dupe of #85 so it should be fixed.

**Comment by anohren** [comment] 2021-06-25 01:45
I hope it will!

Yes, sounds like the same issue. Technically #85 is the dupe.

**Comment by akinwale** [comment] 2021-07-05 18:22
Fixed.

**Closed by akinwale** 2021-07-05 18:22 UTC
